### ISSUE TITLE
Include Spotless Gradle precommit hook

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer-plugins#104]
## Description

OpenSearch's codebase, and by inheritance Wazuh Indexer's, uses a precommit hook to format and lint the Java code using Spotless. In order to guarantee that our plugin's code is consistent and well maintained, we will include this precommit hook to our plugin's `build.gradle`.

The code conventions to be used are the ones defined in the Developer Guide. We will inherit the code and naming conventions from OpenSearch to keep all the codebase consistent.

Explore if we can add a root Grade project to simplify the configuration. The subprojects (each plugin's Gradle project), will inherit the precommit hook from the root project.

## Functional requirements

- Spotless Gradle plugin can be invoked from any of the plugins in this repository.
- Spotless adds missing license headers.
- Spotless runs automatically as a precommit hook.

## Implementation restrictions

- Spotless is added as a Gradle plugin.
- *To avoid duplication, Spotless is added to a root Gradle project. Each of the plugins will be subprojects and will inherit the settings.
- Spotless configuration is decoupled in a separate file (`gradle/formatting.gradle`).
- License headers are imported from a separate file (`license-header.txt`).
- Only code whose group is `com.wazuh` is processed.

\* Optional

## Resources

- https://github.com/opensearch-project/performance-analyzer/blob/1357d86e3936c1de8de951e85f2db792e49d8a02/build.gradle#L89-L104
- https://github.com/opensearch-project/opensearch-plugins/blob/8febf76d863a9608e508603e9b9335b2bc91e437/HEADERS.md
- https://github.com/diffplug/spotless/tree/main/plugin-gradle#java
- https://github.com/wazuh/wazuh-indexer/blob/master/DEVELOPER_GUIDE.md#java-language-formatting-guidelines
- https://github.com/opensearch-project/opensearch-java/blob/a1525e15563552a032af1b02e034fd50d84159a9/buildSrc/src/main/kotlin/opensearch-java.spotless-conventions.gradle.kts#L2
- https://github.com/opensearch-project/sql/blob/e838e46f20c164fe00a907725034ea9896b90f93/plugin/build.gradle#L218
- https://github.com/opensearch-project/k-NN/blob/main/gradle/formatting.gradle

**Comment by QU3B1M** [comment]
Gradle offers [this documentation](https://docs.gradle.org/current/userguide/intro_multi_project_builds.html) that could be useful for the implementation of the generic `build.gradle` to run for all the subprojects (plugins).

For now we will work on a basic implementation of the functionality, so this improvement will be worked on later.

**Comment by QU3B1M** [comment]
The spotless tool is applied and working correctly with the `gradlew` commands, but not the pre-commit hook, for now the implementation is only working on the plugin `command-manager`.

Once the pre-commit hook is working successfully, I will apply the required changes to the other plugin.

**Comment by QU3B1M** [comment]
Spotless was implemented altogether with a git pre-commit hook, also a root Gradle project was initialized to handle generic actions for all the plugins (subprojects)
