### ISSUE TITLE
Error log when creating a PIT search object

### ISSUE THREAD

**Issue by f-galland** [wazuh/wazuh-indexer-plugins#166]
## Description

OpenSearch 2.18.0 introduced a bug on PIT creation that triggers an error log along with a stack trace.
Functionality of the search doesn't seem to be affected, though.

This was already reported in their repository:
* https://github.com/opensearch-project/OpenSearch/issues/16750

**Comment by AlexRuiz7** [comment]
We cannot fix this one, as the warning message is raised by OpenSearch's code. We tried to catch this exception to silence it, but it didn't work. We can only wait for a fix from OpenSearch on a future release.
