### ISSUE TITLE
[BUG] Job Scheduler internal index has replicas

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer-plugins#168]
**Describe the bug**
The internal index of the CM's scheduled job has no settings so it falls back to the default values, which sets 1 replica to the index, causing the cluster to enter the `yellow` state on single node deployments.

**To Reproduce**
1. Run `/_cluster/health`.
2. Run `/_cat/indices/.*?v`.

**Expected behavior**
Cluster stays green.

**Plugins**
Command Manager plugin.

**Host/Environment (please complete the following information):**
 - OS: ['deb', 'rpm']
 - Version ['5.0.0']

**Additional context**
Packages: https://github.com/wazuh/wazuh-indexer/actions/runs/12164433520

**Comment by QU3B1M** [comment]
LGTM! Everything works as expected
