### ISSUE TITLE
Allow Dynamic Fields in `wazuh-alerts-5.x` Index Mapping

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh-indexer-plugins#177]
#### Description
Wazuh-Engine can send events containing fields not currently defined in the `wazuh-alerts-5.x` template mapping. Currently, the index mapping may reject or ignore these extra fields if `dynamic` is set to `false` or `strict`. To accommodate events with new or evolving fields, we need to enable `dynamic` mapping for the `wazuh-alerts-5.x` index. By setting `dynamic: true`, any new fields encountered at ingestion time will be automatically mapped, ensuring that Wazuh-Engine’s variable event structures are properly indexed without requiring frequent template updates.

#### Objectives
- Modify the `wazuh-alerts-5.x` index template in Wazuh-Indexer to set `dynamic`.
- Ensure that any new fields sent by Wazuh-Engine are automatically recognized and indexed by wazuh-indexer.

#### Acceptance Criteria
- Wazuh-Engine events containing new, unmapped fields are successfully indexed without errors.
- Existing functionalities and dashboards are unaffected by this change.
- Documentation reflects the new dynamic mapping behavior.

**Comment by QU3B1M** [comment]
Updated `wazuh-alerts-5.x-*` index ECS mapping settings and its corresponding template on the setup plugin.

Now it can correctly index a custom document on `wazuh-alerts-5.x-*` index:
```bash
curl -X POST "http://127.0.0.1:9200/wazuh-alerts-5.x-0001/_doc" -d '{"agent":{"groups":[],"host":{"architecture":"x86_64","hostname":"chb-VBox","ip":["10.0.2.5","fe80::15c0:9348:3e94:ccc4","192.168.56.102","fe80::f827:ee49:cf2f:e5d4"],"os":{"name":"Ubuntu","type":"Linux","version":"24.04.1 LTS (Noble Numbat)"}},"id":"62541ff0-e035-4615-b0e9-8d0cbbe5592d","name":"chb-VBox","type":"Endpoint","version":"5.0.0"},
"@timestamp":"2024-12-05T18:39:50.582Z","package":{"architecture":"all","description":"root certificates for validating SSL certs and verifying TLS hosts (python3)","installed":null,"name":"python3-certifi","path":" ","size":332800,"type":"deb","version":"2023.11.17-1"}}' -H "Content-Type: application/json"
{"_index":"wazuh-alerts-5.x-0001","_id":"6V5urpMBy7_qefuxNTsT","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1}
```
And the document is correctly retrieved:
```bash
curl "http://127.0.0.1:9200/wazuh-alerts-5.x-0001/_search"     
{"took":3,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":1,"relation":"eq"},"max_score":1.0,"hits":[{"_index":"wazuh-alerts-5.x-0001","_id":"6V5urpMBy7_qefuxNTsT","_score":1.0,"_source":{"agent":{"groups":[],"host":{"architecture":"x86_64","hostname":"chb-VBox","ip":["10.0.2.5","fe80::15c0:9348:3e94:ccc4","192.168.56.102","fe80::f827:ee49:cf2f:e5d4"],"os":{"name":"Ubuntu","type":"Linux","version":"24.04.1 LTS (Noble Numbat)"}},"id":"62541ff0-e035-4615-b0e9-8d0cbbe5592d","name":"chb-VBox","type":"Endpoint","version":"5.0.0"},
"@timestamp":"2024-12-05T18:39:50.582Z","package":{"architecture":"all","description":"root certificates for validating SSL certs and verifying TLS hosts (python3)","installed":null,"name":"python3-certifi","path":" ","size":332800,"type":"deb","version":"2023.11.17-1"}}}]}}
```
