### ISSUE TITLE
Change source code license header

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer-plugins#181]
## Description

The Java code for the `setup` and `command-manager` plugins use an OpenSearch's contributors license header, although that is not the case. The Java code for these plugins must change that license header to Wazuh's. See [LICENSE](https://github.com/wazuh/wazuh-indexer-plugins#AGPL-3.0-1-ov-file).

```java
/*
 * Copyright (C) 2024 Wazuh
 * This file is part of Wazuh Indexer Plugins, which are licensed under the AGPLv3.
 *  See <https://www.gnu.org/licenses/agpl-3.0.txt> for the full text of the license.
*/
```

## Plan

- [x] Change the license headers for every Java class within this repo.
- [x] If required, reconfigure Java Docs check to accept the new license header.

**Comment by QU3B1M** [comment]
Replaced OpenSearch Contributors license header with the Wazuh's AGPL corresponding header
```LICENSE
/*
 * Copyright (C) 2024, Wazuh Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
```
> Using this header instead of the one on the [main comment](https://github.com/wazuh/wazuh-indexer-plugins/issues/181#issue-2732915971) since this is the recommended by the _license_ itself.
