### ISSUE TITLE
Research how to implement a plugin that extends the job-scheduler

### ISSUE THREAD

**Issue by f-galland** [wazuh/wazuh-indexer-plugins#65]
## Description

As part of the command manager development process, we need to understand how to schedule tasks within the Wazuh Indexer.

Some kick-off questions we need to address are:
* How to use `job-scheduler` classes from within other plugins.
* What is the extent of the functionality provided by the `job-scheduler` plugin

After we have a grasp of the above, we can move on to writing code that leverages the job scheduler to run a command periodically.

## Reference links
* [Job Scheduler's readme](https://github.com/opensearch-project/job-scheduler?tab=readme-ov-file#getting-started)
* [Opensearch's documentation page](https://opensearch.org/docs/latest/monitoring-your-cluster/job-scheduler/index/)
* [Sample extension plugin](https://github.com/opensearch-project/job-scheduler/tree/main/sample-extension-plugin)

**Comment by AlexRuiz7** [comment]
The linked PR successfully integrates the opensearch-job-scheduler plugin with our plugin.

The goal of this issue is therefore completed. We will continue learning how to use its features to implement the command manager logic in future issues.
