### ISSUE TITLE
Research configuration persistence methods

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer-plugins#86]
## Description

As part of the development of the Command Manager plugin, we need to investigate which of the methods to persist configuration options for the plugin suits our needs best.

- [x] Main configuration file (`opensearch.yml`).
- [x] Plugin dedicated configuration file.
- [x] Indexer's key store  (`/usr/share/wazuh-indexer/bin/opensearch-keystore` & `/etc/wazuh-indexer/opensearch.keystore`).

The goal of this issue is to:

- Research if the configuration methods above are suitable for the command manager user case. The command manager needs to access information of the Wazuh Server in order to access its Management API (IP, port, user and password (if required)).

**Comment by AlexRuiz7** [comment]
As a conclusion, any configuration file can be loaded on runtime using [Settings](https://github.com/opensearch-project/OpenSearch/blob/2.17.0/server/src/main/java/org/opensearch/common/settings/Settings.java) class builder. The [PluginSettings](https://github.com/opensearch-project/observability/blob/2.17.0.0/src/main/kotlin/org/opensearch/observability/settings/PluginSettings.kt) class from the Observability plugin is a great example of how to define, load and validate plugin specific settings.

```java
Settings.builder().loadFromPath(defaultSettingYmlFile)
```

This method can be used for reading any configuration in the file system.

While taking a look at the Settings class, I noticed the [KeyStoreWrapper](https://github.com/opensearch-project/OpenSearch/blob/2.17.0/server/src/main/java/org/opensearch/common/settings/KeyStoreWrapper.java) class, which presumably can be used to load stuff from the keystore.

We should take a look at it.

**Comment by mcasas993** [comment]
## KeyStoreWrapper class
This class allow us to load an opensearch.keystore file, read the keys and also write new keys. 

The algorithm used to derive the cipher key from a password is "PBKDF2WithHmacSHA512".
The cipher used to encrypt the keystore data is "AES".

### Example in TransportNodesReloadSecureSettingsAction class
```java
 try (KeyStoreWrapper keystore = KeyStoreWrapper.load(environment.configDir())) {
            // reread keystore from config file
            if (keystore == null) {
                return new NodesReloadSecureSettingsResponse.NodeResponse(
                    clusterService.localNode(),
                    new IllegalStateException("Keystore is missing")
                );
            }
            // decrypt the keystore using the password from the request
            keystore.decrypt(secureSettingsPassword.getChars());
            // add the keystore to the original node settings object
            final Settings settingsWithKeystore = Settings.builder().put(environment.settings(), false).setSecureSettings(keystore).build();
            final List<Exception> exceptions = new ArrayList<>();
            // broadcast the new settings object (with the open embedded keystore) to all reloadable plugins
            pluginsService.filterPlugins(ReloadablePlugin.class).stream().forEach(p -> {
                try {
                    p.reload(settingsWithKeystore);
                } catch (final Exception e) {
                    logger.warn(
                        (Supplier<?>) () -> new ParameterizedMessage("Reload failed for plugin [{}]", p.getClass().getSimpleName()),
                        e
                    );
                    exceptions.add(e);
                }
            });
```

### Example in Bootstrap class

```java
static SecureSettings loadSecureSettings(Environment initialEnv) throws BootstrapException {
        final KeyStoreWrapper keystore;
        try {
            keystore = KeyStoreWrapper.load(initialEnv.configDir());
        } catch (IOException e) {
            throw new BootstrapException(e);
        }

        SecureString password;
        try {
            if (keystore != null && keystore.hasPassword()) {
                password = readPassphrase(System.in, KeyStoreAwareCommand.MAX_PASSPHRASE_LENGTH);
            } else {
                password = new SecureString(new char[0]);
            }
        } catch (IOException e) {
            throw new BootstrapException(e);
        }

        try {
            if (keystore == null) {
                final KeyStoreWrapper keyStoreWrapper = KeyStoreWrapper.create();
                keyStoreWrapper.save(initialEnv.configDir(), new char[0]);
                return keyStoreWrapper;
            } else {
                keystore.decrypt(password.getChars());
                KeyStoreWrapper.upgrade(keystore, initialEnv.configDir(), password.getChars());
            }
        } catch (Exception e) {
            throw new BootstrapException(e);
        } finally {
            password.close();
        }
        return keystore;
    }
```

**Comment by AlexRuiz7** [comment]
More uses of the `KeyStoreWrapper` class [here](https://github.com/search?q=org%3Aopensearch-project+KeyStoreWrapper+repo%3Aopensearch-project%2FOpenSearch&type=code&p=1).

We have all the information we need for the next step, which is to implement one of these configuration persistence methods in our `command-manager` plugin. Given our use case, which is to store the URL and credentials of the Management API on the Wazuh Server, I think the key store method fits better, as that's sensitive information.
